-- Santi Onieva

CREATE DATABASE IF NOT EXISTS `Pt04_Santi_Onieva`;

USE `Pt04_Santi_Onieva`;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    alies VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nom_complet VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS articles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titol VARCHAR(255) NOT NULL,
    cos TEXT NOT NULL,
    creat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificat TIMESTAMP DEFAULT NULL,
    autor INT NOT NULL,
    ruta_imatge VARCHAR(255) NOT NULL,

    CONSTRAINT fk_autor FOREIGN KEY (autor) REFERENCES users(id) ON DELETE CASCADE
);